### ISSUE TITLE
lesson 1

### ISSUE THREAD

**Issue by Mayar2009** [jbarrow/allennlp_tutorial#11]
allennlp train --dry-run --include-package tagging -s /tmp/tagging/tests/0 configs/test_reader.jsonnet

could you please explain this line in more details especially /tmp/tagging/tests/0 
where could I find /tmp/tagging/tests/0 
how to read it and how to interpret it?

**Comment by jbarrow** [comment]
Of course! I'll make sure to put this in the guide, but:

`/tmp/tagging/tests/0` is the **serialization directory**. You don't create it (in fact, AllenNLP will crash if you put anything in it); AllenNLP creates it for you when you run the train command.

You can change where the model outputs are saved by changing the serialization directory (the `-s` flag).

Other than that, the footprint of the `allennlp train` command is:

```
allennlp train --include-package [PACKAGE_NAME] -s [SERIALIZATION_DIR] [CONFIG_FILE]
```

Where `PACKAGE_NAME` is the name of the python package (really, the folder) you create to put all the models/predictors/dataset readers into.

In our case, we call it `tagging`.
