### ISSUE TITLE
The pesky error

### ISSUE THREAD

**Issue by jinlukang1** [jbarrow/allennlp_tutorial#3]
Your tutorial is very good！

Is this the pesky error you mentioned in the ‘1. Building a Dataset Reader’?

```allennlp.common.checks.ConfigurationError: 'key "model" is required at location ""'```

**Comment by jbarrow** [comment]
Thanks! 

That is the error, and it shows up because we don’t actually have a model defined by the end of Part 1. I’ll go back and make sure that’s explicit in the text.

**Comment by jbarrow** [comment]
Added in the latest commit!
