### ISSUE TITLE
Raised error while testing reader test_reader.jsonnet

### ISSUE THREAD

**Issue by maliozer** [jbarrow/allennlp_tutorial#4]
I used your configuration then get an error like this any idea ? ;

raise ConfigurationError("The 'vocabulary' directory in the provided "                                              allennlp.common.checks.ConfigurationError: "The 'vocabulary' directory in the provided serialization directory is non-empty"                                                                                                                         

Thanks for your helps :)

**Comment by jbrry** [comment]
AllenNLP throws this ConfigurationError by default if you re-use an existing serialization directory with the `allennlp train` command.

You can either use a different serialization directory or provide the `-f` flag to overwrite the directory contents as mentioned [here](https://github.com/jbarrow/allennlp_tutorial/blob/a50f104787e034d6132f29efc8833bb2fe66a8b9/tutorial/3_Configuring_Experiments.md#33-training).

**Comment by jbarrow** [comment]
To elaborate a little further on the above, the `-f` flag only works when calling `allennlp train`, but not `allennlp dry-run` (in which case you have to delete the serialized directory).
